show_downloads: false
remote_theme: mmistakes/minimal-mistakes@4.21.1
plugins:
- jekyll-remote-theme

author:
  title: Berke Aktaş

links:
  - label: "Linkedin"
    icon: "fab fa-linkedin"
    url: "linkedin.com/in/berke-aktaş-04b9071bb"

  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/ghTaipan"
