title: "Taipan's Blog"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
show_downloads: false

author:
  name: "Berke Aktaş"
  bio: "Sailing the Seven Seas of programming."
  avatar: "/assets/images/avatar.png"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ghTaipan"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/berke-aktaş-04b9071bb"
