show_downloads: false
remote_theme: mmistakes/minimal-mistakes@v4.27.3
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  title: Berke Aktaş

links:
  - label: "Linkedin"
    icon: "fab fa-linkedin"
    url: "linkedin.com/in/berke-aktaş-04b9071bb"

  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/ghTaipan"
